apiVersion: v1
kind: Pod
metadata:
  name: disallowed-pod
spec:
  containers:
  - name: container1
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    hostPath:
      path: /etc
